services:
  postgres:
    container_name: splitiv-postgres
    image: postgres:15-alpine
    environment:
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
